services:
  flare-observer:
    container_name: flare-observer
    image: ghcr.io/flare-foundation/fsp-observer:main
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      RPC_BASE_URL: ${FLARE_RPC_BASE_URL}
      IDENTITY_ADDRESS: ${FLARE_IDENTITY_ADDRESS}
      NOTIFICATION_TELEGRAM_BOT_TOKEN: ${FLARE_NOTIFICATION_TELEGRAM_BOT_TOKEN}
      NOTIFICATION_TELEGRAM_CHAT_ID: ${FLARE_NOTIFICATION_TELEGRAM_CHAT_ID}
      METRICS_ENABLED: ${METRICS_ENABLED}
      METRICS_PORT: ${METRICS_PORT}
      LOG_LEVEL: ${LOG_LEVEL}
      MAX_BLOCK_RANGE: ${MAX_BLOCK_RANGE}
    restart: unless-stopped
    logging:
      driver: local
      options:
        max-size: "2m"
        max-file: "2"
        compress: "true"
